import React, { useEffect, useState } from 'react';
import './poam.css';

const checks = { intune: 'Intune enrollment', configuration: 'Configuration baseline', bitlocker: 'BitLocker protection', defender: 'Defender protection', patching: 'Patch status', localAdmin: 'Local administrator access', deviceCompliance: 'Device compliance review' };
const text = value => (value || 'UNKNOWN').replaceAll('_', ' ');
const platformOf = item => item.review.platform !== 'UNKNOWN' ? item.review.platform : item.observation?.data.operatingSystem ? (item.observation.data.operatingSystem.toUpperCase().startsWith('WINDOWS') ? 'WINDOWS' : 'OTHER') : 'UNKNOWN';
export default function EndpointWorkspace({ runs, screenshots, onDirty, onAuthExpired, onRecordsChanged, onOpenPoam }) {
  const [items, setItems] = useState([]), [id, setId] = useState(() => new URLSearchParams(location.hash.split('?')[1]).get('device') || '');
  const [detail, setDetail] = useState(null), [draft, setDraft] = useState(null), [busy, setBusy] = useState(false);
  const [error, setError] = useState(''), [message, setMessage] = useState('');
  const [query, setQuery] = useState(''), [scope, setScope] = useState(''), [platform, setPlatform] = useState(''), [onlyGaps, setOnlyGaps] = useState(false);
  const [newDevice, setNewDevice] = useState({ name: '', identifier: '' });
  const [gap, setGap] = useState({ run: '', identifier: '', title: '', key: crypto.randomUUID() }), [objectives, setObjectives] = useState([]);
  const dirty = !!draft && !!detail && JSON.stringify(draft) !== JSON.stringify(detail.review);
  const otherDirty = !!(newDevice.name || newDevice.identifier || gap.run || gap.title || gap.identifier);
  useEffect(() => { onDirty(dirty || otherDirty || busy); return () => onDirty(false); }, [dirty, otherDirty, busy]);
  useEffect(() => { const guard = e => { if (dirty || otherDirty || busy) { e.preventDefault(); e.returnValue = ''; } }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty, otherDirty, busy]);
  async function request(url, options) {
    const res = await fetch(url, options); if (res.status === 401) { onAuthExpired(); throw new Error('Please sign in again.'); }
    const data = await res.json(); if (!res.ok) throw new Error(typeof data.detail === 'string' ? data.detail : data.detail?.map(v => v.msg).join('; ') || 'Request failed.'); return data;
  }
  async function refresh() { setItems((await request('/api/endpoints')).items); }
  useEffect(() => { refresh().catch(err => setError(err.message)); }, []);
  useEffect(() => { let cancelled = false; setDetail(null); setDraft(null); setError(''); setMessage(''); if (id) request(`/api/endpoints/${id}`).then(data => { if (!cancelled) { setDetail(data); setDraft(data.review); } }).catch(err => { if (!cancelled) setError(err.message); }); return () => { cancelled = true; }; }, [id]);
  useEffect(() => { let cancelled = false; setObjectives([]); if (gap.run) request(`/api/assessments/${gap.run}/objectives`).then(data => { if (!cancelled) setObjectives(data.items); }).catch(err => { if (!cancelled) setError(err.message); }); return () => { cancelled = true; }; }, [gap.run]);
  function select(value) { if (value === id || busy || ((dirty || otherDirty) && !window.confirm('Discard unsaved endpoint changes?'))) return; setNewDevice({ name: '', identifier: '' }); setGap({ run: '', identifier: '', title: '', key: crypto.randomUUID() }); setId(value); window.history.replaceState(null, '', '#hardware?' + new URLSearchParams({ device: value })); }
  const edit = (key, value) => setDraft(previous => ({ ...previous, [key]: value }));
  async function reload() { if (dirty && !window.confirm('Discard your review draft and reload?')) return; setBusy(true); setError(''); try { const data = await request(`/api/endpoints/${id}`); setDetail(data); setDraft(data.review); await refresh(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); setMessage(''); try { const data = await request(`/api/endpoints/${id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...draft, expected_revision: detail.review.revision, screenshot_ids: draft.screenshots.map(s => s.id), nextReviewDate: draft.nextReviewDate || null }) }); setDetail(data); setDraft(data.review); await refresh(); setMessage('Endpoint review saved.'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function add(e) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/api/inventory', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ asset_type: 'HARDWARE', asset_identifier: newDevice.identifier, name: newDevice.name }) }); setNewDevice({ name: '', identifier: '' }); setId(data.id); window.history.replaceState(null, '', '#hardware?' + new URLSearchParams({ device: data.id })); await refresh(); await onRecordsChanged(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function createGap(e) { e.preventDefault(); setBusy(true); setError(''); try { await request(`/api/endpoints/${id}/poam`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ run_id: gap.run, identifier: gap.identifier, title: gap.title, request_key: gap.key, expected_revision: detail.review.revision }) }); setGap({ run: '', identifier: '', title: '', key: crypto.randomUUID() }); const data = await request(`/api/endpoints/${id}`); setDetail(data); setDraft(data.review); await onRecordsChanged(); setMessage('Linked POA&M created.'); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  const visible = items.filter(item => (!scope || item.review.scope === scope) && (!platform || platformOf(item) === platform) && (!onlyGaps || Object.values(item.review.checks).includes('GAP')) && `${item.name} ${item.assetIdentifier} ${item.review.enclave} ${item.review.owner} ${item.review.assignedUser}`.toLowerCase().includes(query.toLowerCase()));
  const observed = detail?.observation?.data;
  return <div className="poam-workspace"><section className="panel poam-panel"><h2>Endpoint readiness register</h2><p>Cloud enclave scope and Windows PC readiness. Imported signals support human review; they do not set objective decisions.</p><div className="record-grid"><label>Search endpoints<input value={query} onChange={e => setQuery(e.target.value)} placeholder="Device, enclave, owner, or assigned user"/></label><label>Scope filter<select value={scope} onChange={e => setScope(e.target.value)}><option value="">All scopes</option>{['UNKNOWN','IN_SCOPE','OUT_OF_SCOPE'].map(v => <option key={v} value={v}>{text(v)}</option>)}</select></label><label>Platform filter<select value={platform} onChange={e => setPlatform(e.target.value)}><option value="">All hardware</option>{['WINDOWS','OTHER','UNKNOWN'].map(v => <option key={v} value={v}>{text(v)}</option>)}</select></label></div><label className="poam-check"><input type="checkbox" checked={onlyGaps} onChange={e => setOnlyGaps(e.target.checked)}/> Readiness gaps only</label><p>{visible.length} matching endpoints</p><div className="poam-register">{visible.map(item => <button key={item.id} aria-pressed={id === item.id} onClick={() => select(item.id)}><strong>{item.name}</strong><span>{item.review.enclave || 'Enclave unassigned'} · {text(item.review.scope)} · {item.review.owner || 'Owner unassigned'}</span><span>{Object.values(item.review.checks).filter(v => v === 'GAP').length} gaps · {Object.values(item.review.checks).filter(v => v === 'UNKNOWN').length} unknown checks{item.overdue ? ' · Review overdue (UTC)' : ''}</span></button>)}</div>{!visible.length && <p>No matching hardware. Add a device below or use the existing read-only inventory sync.</p>}<button disabled={busy} onClick={() => refresh().catch(err => setError(err.message))}>Refresh endpoints</button>
    <details><summary>Add hardware manually</summary><form onSubmit={add}><fieldset disabled={busy || dirty || !!gap.run || !!gap.title}><div className="record-grid"><label>Device name<input required minLength={2} maxLength={240} value={newDevice.name} onChange={e => setNewDevice({ ...newDevice, name: e.target.value })}/></label><label>Device identifier<input required minLength={2} maxLength={240} value={newDevice.identifier} onChange={e => setNewDevice({ ...newDevice, identifier: e.target.value })} placeholder="Serial number or asset tag"/></label></div><button>Add device</button><button type="button" onClick={() => setNewDevice({ name: '', identifier: '' })}>Discard new device</button></fieldset></form></details></section>
    {error && <div role="alert" className="alert error-alert">{error}</div>}{message && <p role="status">{message}</p>}{id && !detail && !error && <p>Loading endpoint…</p>}
    {draft && detail && <section className="panel poam-panel"><h2>{detail.name}</h2><p>{detail.assetIdentifier}</p><details><summary>Existing inventory context</summary><p>Owner: {detail.inventoryOwner || 'Not recorded'} · Role: {detail.inventoryRole || 'Not recorded'} · Inventory CUI scope: {detail.inventoryCuiInScope ? 'Yes' : 'No'}</p><p>Confirm the enclave scope below; the inventory flag does not replace that review.</p></details>
    <h3>Imported Intune observations</h3>{observed ? <><p>Captured {new Date(detail.observation.observedAt + 'Z').toLocaleString()}. Last device check-in: {observed.lastSyncDateTime || 'Unknown'}. These observations can become stale.</p><dl>{Object.entries({ 'Cloud tenant': observed.tenantId, 'Operating system': observed.operatingSystem, 'OS version': observed.osVersion, 'Assigned user': observed.userPrincipalName, 'Management agent': observed.managementAgent, 'Device compliance': observed.complianceState, 'Device encryption': observed.isEncrypted === true ? 'Reported encrypted' : observed.isEncrypted === false ? 'Reported not encrypted' : 'Unknown' }).map(([k,v]) => <React.Fragment key={k}><dt><b>{k}</b></dt><dd>{v || 'Unknown'}</dd></React.Fragment>)}</dl><p>Device encryption is not a BitLocker configuration assessment. Verify protection, configuration, patching, and local administrator controls below.</p></> : <p>No observation collected yet. Use inventory sync to collect current Intune inventory signals.</p>}
    <form onSubmit={save}><fieldset disabled={busy}><h3>Enclave and assigned users</h3><div className="record-grid">{[['enclave','Enclave name'],['tenantId','Cloud tenant ID'],['owner','Device owner'],['assignedUser','Assigned user']].map(([k,l]) => <label key={k}>{l}<input maxLength={k === 'tenantId' ? 100 : 200} value={draft[k]} onChange={e => edit(k,e.target.value)}/></label>)}<label>Endpoint platform<select value={draft.platform} onChange={e => edit('platform',e.target.value)}>{['UNKNOWN','WINDOWS','OTHER'].map(v => <option key={v} value={v}>{text(v)}</option>)}</select></label><label>Enclave scope<select value={draft.scope} onChange={e => edit('scope',e.target.value)}>{['UNKNOWN','IN_SCOPE','OUT_OF_SCOPE'].map(v => <option key={v} value={v}>{text(v)}</option>)}</select></label><label>Next endpoint review<input type="date" value={draft.nextReviewDate || ''} onChange={e => edit('nextReviewDate',e.target.value)}/></label></div>
    <h3>Reviewer readiness checks</h3><p>Verified means reviewed with supporting evidence. Use Gap for missing controls; there is no exception status.</p><div className="record-grid">{Object.entries(checks).map(([k,l]) => <label key={k}>{l}<select value={draft.checks[k]} onChange={e => edit('checks',{ ...draft.checks,[k]:e.target.value })}>{['UNKNOWN','VERIFIED','GAP'].map(v => <option key={v} value={v}>{text(v)}</option>)}</select></label>)}<label className="wide">Endpoint review rationale<textarea maxLength={20000} value={draft.notes} onChange={e => edit('notes',e.target.value)} placeholder="Describe evidence, verification dates, baseline requirements, and any gaps for each reviewed check."/></label><label className="wide">Endpoint evidence reference<textarea maxLength={5000} value={draft.evidenceReference} onChange={e => edit('evidenceReference',e.target.value)}/></label></div>
    <details><summary>Attach endpoint screenshots</summary>{screenshots.map(shot => <label className="poam-check" key={shot.id}><input type="checkbox" checked={draft.screenshots.some(s => s.id === shot.id)} onChange={e => edit('screenshots',e.target.checked ? [...draft.screenshots,shot] : draft.screenshots.filter(s => s.id !== shot.id))}/>{shot.title}</label>)}</details>{draft.screenshots.map(s => <p key={s.id}><a href={`/api/screenshots/${s.id}/content`} target="_blank" rel="noreferrer">{s.title}</a><small>SHA-256 {s.sha256}</small></p>)}
    <div className="poam-actions"><button disabled={!dirty}>Save endpoint review</button><button type="button" onClick={() => { setDraft(detail.review); setError(''); setMessage(''); }}>Discard endpoint changes</button><button type="button" onClick={reload}>Reload saved endpoint</button></div></fieldset></form>
    <h3>Linked POA&M gaps</h3>{detail.poam.map(p => <p key={p.id}><button disabled={busy} onClick={() => onOpenPoam(p.id)}>{p.title}</button> · {text(p.status)}</p>)}{!detail.poam.length && <p>No linked gaps.</p>}
    {Object.values(detail.review.checks).includes('GAP') ? <form onSubmit={createGap}><fieldset disabled={busy || dirty}><div className="record-grid"><label>Gap assessment<select required value={gap.run} onChange={e => setGap({ ...gap,run:e.target.value,identifier:'' })}><option value="">Select assessment</option>{runs.filter(r => r.tenantId === detail.review.tenantId).map(r => <option key={r.id} value={r.id}>{r.startedAt} · {r.id.slice(0,8)}</option>)}</select></label><label>Gap objective<select required value={gap.identifier} onChange={e => setGap({ ...gap,identifier:e.target.value })}><option value="">Select objective</option>{objectives.map(o => <option key={o.identifier} value={o.identifier}>{o.identifier} · {o.statement}</option>)}</select></label><label>Endpoint gap title<input required minLength={3} maxLength={240} value={gap.title} onChange={e => setGap({ ...gap,title:e.target.value })}/></label></div><button>Create endpoint POA&M</button><button type="button" onClick={() => setGap({ run:'',identifier:'',title:'',key:crypto.randomUUID() })}>Discard gap draft</button></fieldset><p>Save the cloud tenant ID and choose its assessment. The gap inherits the review owner and rationale.</p></form> : <p>Save a readiness check as Gap to create a linked POA&M action.</p>}
    <h3>Endpoint review history</h3>{!detail.history.length && <p>No reviews saved yet.</p>}{detail.history.map(row => <details key={row.revision}><summary>Revision {row.revision} · {row.recordedBy} · {new Date(row.recordedAt+'Z').toLocaleString()}</summary><p>{row.snapshot.enclave} · {row.snapshot.tenantId} · {text(row.snapshot.scope)} · {text(row.snapshot.platform)}</p><p>Owner: {row.snapshot.owner} · Assigned user: {row.snapshot.assignedUser} · Next review: {row.snapshot.nextReviewDate || 'Not set'}</p><ul>{Object.entries(row.snapshot.checks).map(([k,v]) => <li key={k}>{checks[k]}: {text(v)}</li>)}</ul><p style={{whiteSpace:'pre-wrap'}}>{row.snapshot.notes}</p><p>{row.snapshot.evidenceReference}</p>{row.snapshot.screenshots.map(s => <p key={s.id}>{s.title}<small>SHA-256 {s.sha256}</small></p>)}</details>)}
    </section>}
  </div>;
}
